config/routes.rb
Blocipedia::Application.routes.draw do

  resources :invoices, only: [:index]

  resources :wikis do
    resources :collaborators
    end

  resources :charges, only: [:new, :create, :index]
  

  devise_for :users
  root to: 'welcome#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
attr_accessor :stripe_card_token
 
def save_with_payment
  if valid?
    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    self.stripe_customer_token = customer.id
    save!
  end
 
  
   rescue Stripe::APIError => e
      logger.error "Stripe Authentication error while creating user: #{e.message}"
      errors.add :base, "Our system is temporarily unable to process credit cards."
      false
end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  
  belongs_to :wiki_id
  has_many :user_ids
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :roles
  has_many :wikis, through: :roles

  has_many :invoices
  
  def make_premium
    self.update_attribute(:premium, true)
  end 

  def collaborator?
   role == 'collaborator'
  end
 
 def premium_user?
   role == 'premium_user'
 end

 def admin?
  role == 'admin'
 end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  has_many :roles
  has_many :users, through: :roles

  #scope :visible_to, -> (user) { user ? all : where(premium: true) }
  scope :private, lambda { |user| user ? scoped : where(premium: true) }

  def make_premium
    self.update_attribute(:private, true)
  end 

  def collaborators
    self.roles.where(role: "collaborator").includes(:user).collect(&:user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def after_sign_in_path_for(resource)
    root_path
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_filter :authenticate_user!

 
  def new
    @amount = 999
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.name}",
      amount: @amount
    }
  end

  def create
    @amount = 9_99
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.invoices.create(amount: @amount, description: "Premium Membership - #{current_user.email}")
    current_user.update_attribute(:premium, true)
    
    flash[:success] = "Thanks for signing up for a Premium Membership!  You can now create private wikis and add collaborators."
    redirect_to wikis_path
  rescue Stripe:: CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path   
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  attr_accessor :user_id, :wiki_id
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators = Collaborator.where(:id => :wiki_id)
    @collaborators = @wiki.collaborators
  end

  def new
    @wiki = Wiki.find(params[:wiki_id])
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.where(email: params[:email]).first
    if @user.present?
      @wiki.roles.create(role: "collaborator", user_id: @user.id)
      flash[:notice] = "Collaborator was saved successfully."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your collaborator. Please try again."
      render :new
    end
  end


  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    
    if @wiki.roles.where(user_id: params[:id]).first.destroy
      flash[:notice] = "Collaborator was deleted successfully"
      redirect_to @wiki
    else
      flash[:error] = "There was an error deleting your collaborator.  Please try again."
      render :show
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @invoices = current_user.invoices
  end
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
end

app/controllers/roles_controller.rb
class RoleController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_filter :authenticate_user!

  def index
    @wikis = Wiki.all
    authorize @wikis
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    @collaborators = @wiki.collaborators
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Your wiki was saved"
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki.  Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki updated"
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error saving the wiki.  Please try again"
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    title = @wiki.title

    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show 
  end  
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  def markdown(text)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render text).html_safe
end

def syntax_highlighter(html)
  doc = Nokogiri::HTML(html)
  doc.search("//pre[@lang]").each do |pre|
    pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
  end
  doc.to_s
end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/charges/create.html.haml
%h2 Thanks for signing up for a Premium Membership. You can now create private wikis and add collaborators.

app/views/charges/new.html.haml
.container
  = form_tag charges_path do
    %h4 Upgrade to a premium membership!
    %script.stripe-button{"data-amount" => @stripe_btn_data[:amount], "data-key" => @stripe_btn_data[:key], "data-description" => @stripe_btn_data[:description], :src => "https://checkout.stripe.com/checkout.js"}
      :cdata
        @stripe_btn_data[:amount]

app/views/collaborators/_form.html.haml
.container
  .add-collab
    = form_tag wiki_collaborators_path(wiki) do 
      .form-group
      = text_field_tag :name, nil, placeholder: "Name", class: "form-control"
      .form-group
      = text_field_tag :email, nil, placeholder: "Email", class: "form-control"
      .form-group
      = submit_tag "Add Collaborator", class: "btn btn-success btn-sm"

app/views/collaborators/index.html.haml
.container
  %h3
    = @wiki.title
    collaborators
  %table.table.table-striped.table-hover
    %tr
      %thead
        %th{:width => "250px"} Name
        %th{:width => "250px"} Email
        %th{:width => "250px"} Remove from list
      %tr
        - @collaborators.each do |collaborator|
          %tr
            %td= collaborator.name if collaborator
            %td= collaborator.email if collaborator
            %td= link_to "Remove",  wiki_collaborator_url(@wiki, collaborator), method: :delete, class: "btn btn-danger btn-xs"
          %tr
  %br
  = link_to 'New Collaborator', new_wiki_collaborator_path, class: 'btn btn-success btn-sm'
  = link_to 'Back', wiki_path(@wiki), class: 'btn btn-info btn-sm'

app/views/collaborators/new.html.haml
.container
  %h3 Add a collaborator
  .row
    .col-md-4
    = render partial: 'form', locals: { wiki: @wiki } 

app/views/invoices/index.html.haml
.container
  .page-header
    %h4 Past Invoices
    %table.table.table-striped.table-hover.invoices
      %thead
        %tr
          %th Amount
          %th Paid in
      %tbody
        - @invoices.each do |invoice|
          %tr
            %td= number_to_currency(invoice.amount / 100.0)
            %td= invoice.created_at.to_s(:long)
    %br
    = link_to "Pay your membership", new_charge_path, class: 'btn btn-success btn-sm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocipedia
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "https://js.stripe.com/v1/", "application", "data-turbolinks-track" => true
    = javascript_include_tag "//kristingonzalez-blocmetrics.herokuapp.com/agent.js"
    %meta{name: "verification_code", content: "1e550d9263e141e301ab0ea3b3e0eed076a40cefb7c9baa80ee0ba11da14"}
    %meta{name: "authentication_token", content: "yXXmBvR24LM32swQxxzkrePuphZjM-Z4hA"}
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-default
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.nav-pills
            %li= link_to "Home", root_path
            %li= link_to "Wikis", wikis_path
            %li= link_to "Invoices", invoices_path
            %li= link_to "Upgrade today", new_charge_path
            .pull-right.user-info
              - if current_user
                Hello #{current_user.email}! #{link_to "Sign out", destroy_user_session_path, method: :delete}
              - else
                = link_to "Sign in", new_user_session_path
                or
                \#{link_to "Sign up", new_user_registration_path} 
    
    - if flash[:notice]
      .alert.alert-success
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:notice]
    - elsif flash[:error]
      .alert.alert-danger
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:error]
    - elsif flash[:alert]
      .alert.alert-warning
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:alert]
    = yield

app/views/welcome/index.html.haml
%body
  .container
    .jumbotron
      %h1
        Blocipedia
        %p
          Blocipedia is a place to share ideas and collaborate with friends  
          = link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-sm'
          or
          \#{link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-sm'} today!
    .row
      .col-md-6
        %h3 Public Wikis
        %p Create public wikis to share with the world! 
        %br
        %h3 Markdown Support
        %p
          Write your wikis with easy-to-use 
          %a{:href => "http://daringfireball.net/projects/markdown/"} Markdown.
      .col-md-6
        %h3 Private Wikis
        %p 
          Create private wikis as a Blocipedia 
          = link_to "premium member", new_charge_path
        %br
        %h3 Group Collaboration
        %p 
          Work with your 
          %strong dream team 
          to build your wiki.

app/views/wikis/_form.html.haml
= form_for @wiki do |f|
  .form-group
  = f.label :title
  = f.text_field :title, class: 'form-control'
  .form-group
  = f.label :body
  =f.text_area :body, rows: 8, class: 'form-control'
  .form-group
  = f.label :private, "Private"
  = f.check_box :private

  %br
  =f.submit "Save", class: 'btn btn-success btn-sm'

app/views/wikis/edit.html.haml
.container
  .wiki-edit
    %h3= markdown @wiki.title
    %p= markdown @wiki.body
    %br
    %h3 Edit wiki
    %row
      .col-md-4
      .col-md-8
    - if policy(@wiki).edit?
      = render partial: 'form', locals: { wiki: @wiki}
    %br
      = link_to "Back to #{@wiki.title}", wiki_path(@wiki), class: 'btn btn-default btn-sm'

app/views/wikis/index.html.haml
.container
  .wikis-index
    %h3 Wikis
    %ul.list-group
    -@wikis.each do |wiki|
      %h4.media-headingli.list-group-item
        = link_to wiki.title, wiki_path(wiki)
        .col-md-offset-1
        %small Created #{time_ago_in_words(wiki.created_at)} ago by #{current_user.name}
    %br
    - if policy(Wiki.new).create?
      = link_to "Add wiki", new_wiki_path, class: 'btn btn-success btn-sm'

app/views/wikis/new.html.haml
.container
  %h3 Add your wiki
  .row
    .col-md-4
    .col-md-8
  = render partial: 'form', locals: { wiki: @wiki} 

app/views/wikis/show.html.haml
.container
  .wiki-show
    %h3.col.md-6= markdown @wiki.title
    %p= markdown @wiki.body
    %br
    = link_to "Edit wiki", edit_wiki_path(@wiki), class: 'btn btn-success btn-sm'
    = link_to "Delete wiki", @wiki, method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: 'Are you sure you want to delete this wiki?'}
    = link_to "All wikis", wikis_path(@wikis), class: 'btn btn-default btn-sm'
    = link_to "View Collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-warning btn-sm'
    = link_to "Add Collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-info btn-sm'

    %hr
    -if @wiki.private?
      .badge.badge-info
        This is a private wiki.